Really basics raw comparisons on the same computer...

* https://blog.logrocket.com/an-introduction-to-profiling-a-rust-web-application/


`./start-release.sh`

== WARP

[source,raw]
....
   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   152.31ms   52.22ms 353.26ms   74.33%
    Req/Sec   132.20     54.66   333.00     68.30%
  47418 requests in 30.10s, 25.01MB read
  Socket errors: connect 155, read 83, write 3, timeout 0
Requests/sec:   1575.39
Transfer/sec:    850.77KB

   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   180.20ms   88.65ms   1.64s    90.36%
    Req/Sec   151.52     78.17   530.00     60.73%
  40331 requests in 30.08s, 21.27MB read
  Socket errors: connect 155, read 4, write 0, timeout 0
Requests/sec:   1340.61
Transfer/sec:    723.98KB

....

== ACTIX

`RUST_LOG="jwtd=debug"`

[source, raw]
....
   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   582.60ms  336.08ms   1.97s    72.70%
    Req/Sec    36.67     25.36   200.00     68.40%
  11687 requests in 30.09s, 6.15MB read
  Socket errors: connect 155, read 219, write 0, timeout 50
  Non-2xx or 3xx responses: 23
Requests/sec:    388.40
Transfer/sec:    209.42KB
....

[source,raw]
....
   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   950.41ms  395.26ms   1.99s    68.17%
    Req/Sec    22.36     19.60   220.00     88.46%
  6897 requests in 30.10s, 3.62MB read
  Socket errors: connect 155, read 247, write 0, timeout 85
  Non-2xx or 3xx responses: 51
Requests/sec:    229.15
Transfer/sec:    123.01KB
....

`RUST_LOG="jwtd=info"`
