Really basics raw comparisons on the same computer...

* https://blog.logrocket.com/an-introduction-to-profiling-a-rust-web-application/


`./start-release.sh`

== WARP

[source,raw]
....
  ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   151.27ms   61.95ms 350.24ms   61.19%
    Req/Sec   134.78     89.30   410.00     57.00%
  47729 requests in 30.10s, 25.17MB read
  Socket errors: connect 155, read 75, write 9, timeout 0
Requests/sec:   1585.62
Transfer/sec:    856.29KB

   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   162.17ms   65.71ms 610.30ms   57.21%
    Req/Sec   169.09    107.51   705.00     53.81%
  44469 requests in 30.09s, 23.45MB read
  Socket errors: connect 155, read 1, write 3, timeout 0
Requests/sec:   1477.68
Transfer/sec:    798.01KB
....

== ACTIX

`RUST_LOG="jwtd=debug"`

[source, raw]
....
   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   151.66ms   78.78ms   1.98s    95.59%
    Req/Sec   181.36     91.33   370.00     60.74%
  47841 requests in 30.10s, 25.23MB read
  Socket errors: connect 155, read 60, write 0, timeout 3
Requests/sec:   1589.53
Transfer/sec:    858.41KB

   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   145.08ms   25.14ms 272.36ms   90.39%
    Req/Sec   174.40    113.42   570.00     54.11%
  48702 requests in 30.09s, 25.68MB read
  Socket errors: connect 155, read 65, write 0, timeout 0
Requests/sec:   1618.68
Transfer/sec:      0.85MB
....

`RUST_LOG="jwtd=info"`
