Really basics raw comparisons on the same computer...

* https://blog.logrocket.com/an-introduction-to-profiling-a-rust-web-application/


`./start-release.sh`

== WARP

[source,raw]
....
  ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   151.27ms   61.95ms 350.24ms   61.19%
    Req/Sec   134.78     89.30   410.00     57.00%
  47729 requests in 30.10s, 25.17MB read
  Socket errors: connect 155, read 75, write 9, timeout 0
Requests/sec:   1585.62
Transfer/sec:    856.29KB

   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   162.17ms   65.71ms 610.30ms   57.21%
    Req/Sec   169.09    107.51   705.00     53.81%
  44469 requests in 30.09s, 23.45MB read
  Socket errors: connect 155, read 1, write 3, timeout 0
Requests/sec:   1477.68
Transfer/sec:    798.01KB
....

== ACTIX


[source, raw]
....
   ./perf.sh
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   154.20ms   59.84ms   1.75s    97.96%
    Req/Sec   129.74     55.37   340.00     68.15%
  46576 requests in 30.10s, 24.56MB read
  Socket errors: connect 155, read 60, write 0, timeout 0
Requests/sec:   1547.19
Transfer/sec:    835.54KB

   ./perf.sh
perf_scripts/sign.lua: cannot open perf_scripts/sign.lua: Too many open files
Running 30s test @ http://127.0.0.1:8080/sign
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   160.77ms   80.21ms   1.97s    98.05%
    Req/Sec   172.05     78.99   350.00     64.58%
  44977 requests in 30.08s, 23.72MB read
  Socket errors: connect 155, read 65, write 0, timeout 4
Requests/sec:   1495.34
Transfer/sec:    807.54KB
....
