name: Release
on:
  push:
    tags: [ "v**" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate a changelog
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          args: --latest

      - name: Create Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}